In [172]:
from requests import get
from requests.exceptions import RequestException
from contextlib import closing
from bs4 import BeautifulSoup
import pandas as pd

In [177]:
# Pretend to be a web browser and make a get request of a webpage
wine_request = get('https://www.wine.com/list/wine/7155')

In [178]:
wine_request.status_code

200

In [208]:
global product

def read_wine_page(wine_request):
    # The .text returns the text from the request
    wine_html = wine_request.text
    # Then make the soup, specifying the "lxml" parser
    house_soup = BeautifulSoup(wine_html,'lxml')
    mydivs = house_soup.findAll("div", {"class": "prodItem_wrap"})

    wineNames = []
    wineImgs = []
    winePrices = []
    wineUrls = []
    raw_htmls = []
    
    for product in mydivs:
        wineNames.append(product.find('span', {'class' : 'prodItemInfo_name'}).text)
        wineImgs.append(str(product.find('img')).split('src=')[1].split('/>')[0].replace('"', ''))
        winePrices.append(float(str(product.find('div', {'class' : 'prodItemStock_addCart'}))\
                                    .split('data-unit=')[1]\
                                    .split('>')[0]\
                                    .replace('"', '')\
                                    .replace('$','')\
                                    .replace(',','')))
        wineUrls.append(product.find('a', {'class' : 'prodItemImage_link'})['href'])
        raw_htmls.append(str(product))
    
    
    winePage_df = pd.DataFrame(data=[wineNames,
                                     wineImgs,
                                     winePrices,
                                     wineUrls,
                                     raw_htmls]).transpose()
    winePage_df.columns = ['name','image_path','price','url','raw_html']
    
    return winePage_df

In [195]:
product.find('div', {'class' : 'prodItemStock_addCart'})['data-unit']

'$44.99'

In [200]:
winePage_df.head()

,Name,Image_Link,Price
0,Hall Napa Valley Cabernet Sauvignon 2013,/product/images/fl_progressive/158457.jpg,54.99
1,Rombauer Chardonnay 2017,/product/images/fl_progressive/wpxkrgx7onirby1...,36.99
2,Chateau Cos d'Estournel (Futures Pre-Sale) 2016,/product/images/fl_progressive/202293.jpg,219.97
3,Silver Oak Napa Valley Cabernet Sauvignon 2014,/product/images/fl_progressive/fog0sb2avopbbq0...,119.99
4,Silver Oak Alexander Valley Cabernet Sauvignon...,/product/images/fl_progressive/gpgmugpbf3l6is2...,74.99

In [207]:
type(wine_master_df)

tuple

In [ ]:
wine_page_ix = 1
while True:
    if wine_page_ix == 1:
        get_response = get('https://www.wine.com/list/wine/7155')
        wine_master_df = read_wine_page(get_response)
        wine_page_ix += 1
        
    # Pull request and check if OK response
    get_response = get('https://www.wine.com/list/wine/7155/{}'.format(wine_page_ix))
    temp_df = read_wine_page(get_response)
    if get_response.status_code != 200 or temp_df.shape[0] < 20:
        print("Finished pulling data, found {} status code".format(get_response.status_code))
        break
    
    # Append results
    wine_master_df = pd.concat([wine_master_df,temp_df], axis=0)
    print("{}: df shape: {}".format(wine_page_ix, wine_master_df.shape))
    wine_page_ix += 1

2: df shape: (50, 5)
3: df shape: (75, 5)
4: df shape: (100, 5)
5: df shape: (125, 5)
6: df shape: (150, 5)
7: df shape: (175, 5)
8: df shape: (200, 5)
9: df shape: (225, 5)
10: df shape: (250, 5)
11: df shape: (275, 5)
12: df shape: (300, 5)
13: df shape: (325, 5)
14: df shape: (350, 5)
15: df shape: (375, 5)
16: df shape: (400, 5)
17: df shape: (425, 5)
18: df shape: (450, 5)
19: df shape: (475, 5)
20: df shape: (500, 5)
21: df shape: (525, 5)
22: df shape: (550, 5)
23: df shape: (575, 5)
24: df shape: (600, 5)
25: df shape: (625, 5)
26: df shape: (650, 5)
27: df shape: (675, 5)
28: df shape: (700, 5)
29: df shape: (725, 5)
30: df shape: (750, 5)
31: df shape: (775, 5)
32: df shape: (800, 5)
33: df shape: (825, 5)
34: df shape: (850, 5)
35: df shape: (875, 5)
36: df shape: (900, 5)
37: df shape: (925, 5)
38: df shape: (950, 5)
39: df shape: (975, 5)
40: df shape: (1000, 5)
41: df shape: (1025, 5)
42: df shape: (1050, 5)
43: df shape: (1075, 5)
44: df shape: (1100, 5)
45: df shape: (1125, 5)
46: df shape: (1150, 5)
47: df shape: (1175, 5)
48: df shape: (1200, 5)
49: df shape: (1225, 5)
50: df shape: (1250, 5)
51: df shape: (1275, 5)
52: df shape: (1300, 5)
53: df shape: (1325, 5)
54: df shape: (1350, 5)
55: df shape: (1375, 5)
56: df shape: (1400, 5)
57: df shape: (1425, 5)
58: df shape: (1450, 5)
59: df shape: (1475, 5)
60: df shape: (1500, 5)
61: df shape: (1525, 5)
62: df shape: (1550, 5)
63: df shape: (1575, 5)
64: df shape: (1600, 5)
65: df shape: (1625, 5)
66: df shape: (1650, 5)
67: df shape: (1675, 5)
68: df shape: (1700, 5)
69: df shape: (1725, 5)
70: df shape: (1750, 5)
71: df shape: (1775, 5)
72: df shape: (1800, 5)
73: df shape: (1825, 5)
74: df shape: (1850, 5)
75: df shape: (1875, 5)
76: df shape: (1900, 5)
77: df shape: (1925, 5)
78: df shape: (1950, 5)
79: df shape: (1975, 5)
80: df shape: (2000, 5)
81: df shape: (2025, 5)
82: df shape: (2050, 5)
83: df shape: (2075, 5)
84: df shape: (2100, 5)
85: df shape: (2125, 5)
86: df shape: (2150, 5)
87: df shape: (2175, 5)
88: df shape: (2200, 5)
89: df shape: (2225, 5)
90: df shape: (2250, 5)
91: df shape: (2275, 5)
92: df shape: (2300, 5)
93: df shape: (2325, 5)
94: df shape: (2350, 5)
95: df shape: (2375, 5)
96: df shape: (2400, 5)
97: df shape: (2425, 5)
98: df shape: (2450, 5)
99: df shape: (2475, 5)
100: df shape: (2500, 5)
101: df shape: (2525, 5)
102: df shape: (2550, 5)
103: df shape: (2575, 5)
104: df shape: (2600, 5)
105: df shape: (2625, 5)
106: df shape: (2650, 5)
107: df shape: (2675, 5)
108: df shape: (2700, 5)
109: df shape: (2725, 5)
110: df shape: (2750, 5)
111: df shape: (2775, 5)
112: df shape: (2800, 5)
113: df shape: (2825, 5)
114: df shape: (2850, 5)
115: df shape: (2875, 5)
116: df shape: (2900, 5)
117: df shape: (2925, 5)
118: df shape: (2950, 5)
119: df shape: (2975, 5)
120: df shape: (3000, 5)
121: df shape: (3025, 5)
122: df shape: (3050, 5)
123: df shape: (3075, 5)
124: df shape: (3100, 5)
125: df shape: (3125, 5)
126: df shape: (3150, 5)
127: df shape: (3175, 5)
128: df shape: (3200, 5)
129: df shape: (3225, 5)
130: df shape: (3250, 5)
131: df shape: (3275, 5)
132: df shape: (3300, 5)
133: df shape: (3325, 5)
134: df shape: (3350, 5)
135: df shape: (3375, 5)
136: df shape: (3400, 5)
137: df shape: (3425, 5)
138: df shape: (3450, 5)
139: df shape: (3475, 5)
140: df shape: (3500, 5)
141: df shape: (3525, 5)
142: df shape: (3550, 5)
143: df shape: (3575, 5)
144: df shape: (3600, 5)
145: df shape: (3625, 5)
146: df shape: (3650, 5)
147: df shape: (3675, 5)
148: df shape: (3700, 5)
149: df shape: (3725, 5)
150: df shape: (3750, 5)
151: df shape: (3775, 5)
152: df shape: (3800, 5)
153: df shape: (3825, 5)
154: df shape: (3850, 5)
155: df shape: (3875, 5)
156: df shape: (3900, 5)
157: df shape: (3925, 5)
158: df shape: (3950, 5)
159: df shape: (3975, 5)
160: df shape: (4000, 5)
161: df shape: (4025, 5)
162: df shape: (4050, 5)
163: df shape: (4075, 5)
164: df shape: (4100, 5)
165: df shape: (4125, 5)
166: df shape: (4150, 5)
167: df shape: (4175, 5)
168: df shape: (4200, 5)
169: df shape: (4225, 5)
170: df shape: (4250, 5)
171: df shape: (4275, 5)
172: df shape: (4300, 5)
173: df shape: (4325, 5)
174: df shape: (4350, 5)
175: df shape: (4375, 5)
176: df shape: (4400, 5)
177: df shape: (4425, 5)
178: df shape: (4450, 5)
179: df shape: (4475, 5)
180: df shape: (4500, 5)
181: df shape: (4525, 5)
182: df shape: (4550, 5)
183: df shape: (4575, 5)
184: df shape: (4600, 5)
185: df shape: (4625, 5)
186: df shape: (4650, 5)
187: df shape: (4675, 5)
188: df shape: (4700, 5)
189: df shape: (4725, 5)
190: df shape: (4750, 5)
191: df shape: (4775, 5)
192: df shape: (4800, 5)
193: df shape: (4825, 5)
194: df shape: (4850, 5)
195: df shape: (4875, 5)
196: df shape: (4900, 5)
197: df shape: (4925, 5)
198: df shape: (4950, 5)
199: df shape: (4975, 5)
200: df shape: (5000, 5)
201: df shape: (5025, 5)
202: df shape: (5050, 5)
203: df shape: (5075, 5)
204: df shape: (5100, 5)
205: df shape: (5125, 5)
206: df shape: (5150, 5)
207: df shape: (5175, 5)
208: df shape: (5200, 5)
209: df shape: (5225, 5)
210: df shape: (5250, 5)
211: df shape: (5275, 5)
212: df shape: (5300, 5)
213: df shape: (5325, 5)
214: df shape: (5350, 5)
215: df shape: (5375, 5)
216: df shape: (5400, 5)
217: df shape: (5425, 5)
218: df shape: (5450, 5)
219: df shape: (5475, 5)
220: df shape: (5500, 5)
221: df shape: (5525, 5)
222: df shape: (5550, 5)
223: df shape: (5575, 5)
224: df shape: (5600, 5)
225: df shape: (5625, 5)
226: df shape: (5650, 5)
227: df shape: (5675, 5)
228: df shape: (5700, 5)
229: df shape: (5725, 5)
230: df shape: (5750, 5)
231: df shape: (5775, 5)
232: df shape: (5800, 5)
233: df shape: (5825, 5)
234: df shape: (5850, 5)
235: df shape: (5875, 5)
236: df shape: (5900, 5)
237: df shape: (5925, 5)
238: df shape: (5950, 5)
239: df shape: (5975, 5)
240: df shape: (6000, 5)
241: df shape: (6025, 5)
242: df shape: (6050, 5)
243: df shape: (6075, 5)
244: df shape: (6100, 5)
245: df shape: (6125, 5)
246: df shape: (6150, 5)
247: df shape: (6175, 5)
248: df shape: (6200, 5)
249: df shape: (6225, 5)
250: df shape: (6250, 5)
251: df shape: (6275, 5)
252: df shape: (6300, 5)
253: df shape: (6325, 5)
254: df shape: (6350, 5)
255: df shape: (6375, 5)
256: df shape: (6400, 5)
257: df shape: (6425, 5)
258: df shape: (6450, 5)
259: df shape: (6475, 5)
260: df shape: (6500, 5)
261: df shape: (6525, 5)
262: df shape: (6550, 5)
263: df shape: (6575, 5)
264: df shape: (6600, 5)
265: df shape: (6625, 5)
266: df shape: (6650, 5)
267: df shape: (6675, 5)
268: df shape: (6700, 5)
269: df shape: (6725, 5)
270: df shape: (6750, 5)
271: df shape: (6775, 5)
272: df shape: (6800, 5)
273: df shape: (6825, 5)
274: df shape: (6850, 5)
275: df shape: (6875, 5)
276: df shape: (6900, 5)
277: df shape: (6925, 5)
278: df shape: (6950, 5)
279: df shape: (6975, 5)
280: df shape: (7000, 5)
281: df shape: (7025, 5)
282: df shape: (7050, 5)
283: df shape: (7075, 5)
284: df shape: (7100, 5)
285: df shape: (7125, 5)
286: df shape: (7150, 5)
287: df shape: (7175, 5)
288: df shape: (7200, 5)
289: df shape: (7225, 5)
290: df shape: (7250, 5)
291: df shape: (7275, 5)
292: df shape: (7300, 5)
293: df shape: (7325, 5)
294: df shape: (7350, 5)
295: df shape: (7375, 5)
296: df shape: (7400, 5)
297: df shape: (7425, 5)
298: df shape: (7450, 5)
299: df shape: (7475, 5)
300: df shape: (7500, 5)
301: df shape: (7525, 5)
302: df shape: (7550, 5)
303: df shape: (7575, 5)
304: df shape: (7600, 5)
305: df shape: (7625, 5)
306: df shape: (7650, 5)
307: df shape: (7675, 5)
308: df shape: (7700, 5)
309: df shape: (7725, 5)
310: df shape: (7750, 5)
311: df shape: (7775, 5)
312: df shape: (7800, 5)
313: df shape: (7825, 5)
314: df shape: (7850, 5)
315: df shape: (7875, 5)
316: df shape: (7900, 5)
317: df shape: (7925, 5)
318: df shape: (7950, 5)
319: df shape: (7975, 5)
320: df shape: (8000, 5)
321: df shape: (8025, 5)
322: df shape: (8050, 5)
323: df shape: (8075, 5)
324: df shape: (8100, 5)
325: df shape: (8125, 5)
326: df shape: (8150, 5)
327: df shape: (8175, 5)
328: df shape: (8200, 5)
329: df shape: (8225, 5)
330: df shape: (8250, 5)
331: df shape: (8275, 5)
332: df shape: (8300, 5)
333: df shape: (8325, 5)
334: df shape: (8350, 5)
335: df shape: (8375, 5)
336: df shape: (8400, 5)
337: df shape: (8425, 5)
338: df shape: (8450, 5)
339: df shape: (8475, 5)
340: df shape: (8500, 5)
341: df shape: (8525, 5)
342: df shape: (8550, 5)
343: df shape: (8575, 5)
344: df shape: (8600, 5)
345: df shape: (8625, 5)
346: df shape: (8650, 5)
347: df shape: (8675, 5)
348: df shape: (8700, 5)
349: df shape: (8725, 5)
350: df shape: (8750, 5)
351: df shape: (8775, 5)
352: df shape: (8800, 5)
353: df shape: (8825, 5)
354: df shape: (8850, 5)
355: df shape: (8875, 5)
356: df shape: (8900, 5)
357: df shape: (8925, 5)
358: df shape: (8950, 5)
359: df shape: (8975, 5)
360: df shape: (9000, 5)
361: df shape: (9025, 5)
362: df shape: (9050, 5)
363: df shape: (9075, 5)
364: df shape: (9100, 5)
365: df shape: (9125, 5)
366: df shape: (9150, 5)
367: df shape: (9175, 5)
368: df shape: (9200, 5)
369: df shape: (9225, 5)
370: df shape: (9250, 5)
371: df shape: (9275, 5)
372: df shape: (9300, 5)
373: df shape: (9325, 5)
374: df shape: (9350, 5)
375: df shape: (9375, 5)
376: df shape: (9400, 5)
377: df shape: (9425, 5)
378: df shape: (9450, 5)
379: df shape: (9475, 5)
380: df shape: (9500, 5)
381: df shape: (9525, 5)
382: df shape: (9550, 5)
383: df shape: (9575, 5)
384: df shape: (9600, 5)
385: df shape: (9625, 5)
386: df shape: (9650, 5)
387: df shape: (9675, 5)
388: df shape: (9700, 5)
389: df shape: (9725, 5)
390: df shape: (9750, 5)
391: df shape: (9775, 5)
392: df shape: (9800, 5)
393: df shape: (9825, 5)
394: df shape: (9850, 5)
395: df shape: (9875, 5)
396: df shape: (9900, 5)
397: df shape: (9925, 5)
398: df shape: (9950, 5)
399: df shape: (9975, 5)
400: df shape: (10000, 5)
401: df shape: (10025, 5)
402: df shape: (10050, 5)
403: df shape: (10075, 5)
404: df shape: (10100, 5)
405: df shape: (10125, 5)
406: df shape: (10150, 5)
407: df shape: (10175, 5)
408: df shape: (10200, 5)

In [215]:
wine_master_df.to_pickle('data/scrape_v2.pickle')

In [214]:
wine_master_df.drop_duplicates().shape

(25, 5)